---
repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        files: '\.(js|jsx|ts|tsx)$'
        entry: npx eslint --fix
        pass_filenames: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--settings", "backend/setup.cfg"]
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--config", "backend/setup.cfg"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        args: ["--pretty", "--config-file", "backend/setup.cfg"]
  - repo: local
    hooks:
      - id: generate-fetchers
        name: generate-fetchers
        entry: hooks/hook_generate-fetchers.sh
        language: script
        pass_filenames: false
