version: "3.9"

services:
  streams-explorer:
    image: bakdata/streams-explorer
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8083:8083"
      - "9090:9090"
    volumes:
      - ~/.kube/config:/app/kubeconfig
    environment:
      - KUBECONFIG=/app/kubeconfig
      - SE_K8S__deployment__cluster=false
      - SE_K8S__deployment__context=kubernetes-cluster
      - SE_K8S__deployment__namespaces=['kubernetes-namespace1', 'kubernetes-namespace2']
      - SE_SCHEMAREGISTRY__url=http://host.docker.internal:8081
      - SE_KAFKACONNECT__url=http://host.docker.internal:8083
      - SE_PROMETHEUS__url=http://host.docker.internal:9090
