# :schema https://mise.jdx.dev/schema/mise.json
[tools]
python = "3.10"
node = "24"

[env]
VIRTUAL_ENV = "{{config_root}}/backend/.venv"
_.path = [
  "{{config_root}}/backend/.venv/bin",
  "{{config_root}}/frontend/node_modules/.bin",
]
