image: "bakdata/streams-explorer"
imageTag: "latest"
imagePullSecrets: []
# - name: "image-pull-secret"

replicaCount: 1
imagePullPolicy: Always
serviceHttpPort: 8080

# Configure using env variables
config:
  K8S__deployment__cluster: true
  # SCHEMAREGISTRY__url: http://schema-registry:8081
  # KAFKACONNECT__url: http://kafka-connect:8083
  # PROMETHEUS__url: http://prometheus:9090

# Or pass the whole settings.yaml as a configmap
# settings:
#   k8s:
#     deployment:
#       cluster: true
#   ...

envPrefix: "SE_"

# Configure secret env variables here
secrets: {}

annotations: {}

# Configure custom volumeMounts
volumeMounts: []

# Configure custom volumes
volumes: []

# Add plugins
plugins: {}
# example_linking_service: |
#   def class Linking(LinkingService):
#     ...

# Add icons for sources or sinks added with custom extractor plugins
icons: {}
# example_icon: |
#   <svg></svg>

deploymentLabels: {}

podLabels: {}
service:
  type: ClusterIP

# Create a role and role binding to scrape only the namespace
# the Streams Explorer is deployed to.
# To scrape multiple namespaces create a cluster role and
# multiple role bindings.
rbac:
  create: true
  # useExistingRole: "streams-explorer-role"
  # useExistingServiceAccount: "streams-explorer-sa"
  clusterScope:
    enabled: false
    namespaces: ["kubernetes-namespace"]

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: sample.dev.daaa.cloud
      paths:
        - path: /
          # pathType: ImplementationSpecific
          # serviceName:
          # servicePort:
  tls: []
  # Commonly used to map ingress objects to specific ingress controller installations within your cluster
  #ingressClassName: nginx-web-ingress

resources:
  requests:
    cpu: 200m
    memory: 300Mi
  limits:
    memory: 2G
    cpu: 500m

health:
  livenessProbeInitialDelay: 30
  livenessProbePeriodSeconds: 15
  livenessProbeTimeout: 30
  livenessProbeFailureThreshold: 3
  livenessProbeSuccessThreshold: 1
  readinessProbeInitialDelay: 30
  readinessProbePeriodSeconds: 5
  readinessProbeTimeout: 30
  readinessProbeFailureThreshold: 3
  readinessProbeSuccessThreshold: 1

# nodeAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#     nodeSelectorTerms:
#     - matchExpressions:
#       - key: foo
#         operator: In
#         values:
#         - bar
#         - baz
#   preferredDuringSchedulingIgnoredDuringExecution:
#   - weight: 1
#     preference:
#       matchExpressions:
#       - key: foo
#         operator: In
#         values:
#         - bar
#         - baz
