image: "bakdata/streams-explorer"
imageTag: "latest"
imagePullSecrets: []
# - name: "image-pull-secret"

replicaCount: 1
imagePullPolicy: Always
serviceHttpPort: 80

# Configure env variables here
env:
    MAX_WORKERS: '1'  # Max number of FastAPI worker processes inside the pod
    SE_SCHEMAREGISTRY__url: 'http://schema-registry:8081'
    SE_KAFKACONNECT__url: 'http://kafka-connect:8083'
    SE_PROMETHEUS__url: 'http://prometheus:9090'
    SE_K8S__deployment__cluster: true
    SE_K8S__deployment__context: 'kubernetes-cluster'
    SE_K8S__deployment__namespaces: "['kubernetes-namespace']"

# Configure secret env variables here
secrets: {}

annotations: {}

# Configure custom volumeMounts
volumeMounts: []

# Configure custom volumes
volumes: []

# Add plugins
plugins: {}
# example_linking_service: |
#   def class Linking(LinkingService):
#     ...

# Add icons for sources or sinks added with custom extractor plugins
icons: {}
# example_icon: |
#   <svg></svg>


deploymentLabels: {}

podLabels: {}
service:
  type: ClusterIP

# Create a service account, role binding and role to list/get/watch all deployments in the same namespace the explorer is deployed to. To support different namespaces, you need to set up a service account manually.
serviceAccount:
  create: true
  name: "streams-explorer-sa"

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - sample.dev.daaa.cloud
  tls: []
  # Redirect http to https: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/tasks/ssl_redirect/
  sslRedirect: true

resources:
  requests:
    cpu: 200m
    memory: 300Mi
  limits:
    memory: 2G
    cpu: 500m

health:
  livenessProbeInitialDelay: 30
  livenessProbePeriodSeconds: 15
  livenessProbeTimeout: 30
  livenessProbeFailureThreshold: 3
  livenessProbeSuccessThreshold: 1
  readinessProbeInitialDelay: 30
  readinessProbePeriodSeconds: 5
  readinessProbeTimeout: 30
  readinessProbeFailureThreshold: 3
  readinessProbeSuccessThreshold: 1
