/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Streams Explorer
 * OpenAPI spec version: 0.1.0
 */
import type { Edge } from './edge';
import type { Node } from './node';

export interface Graph {
  directed: boolean;
  multigraph: boolean;
  graph?: unknown;
  nodes: Node[];
  edges: Edge[];
}
