/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Streams Explorer
 * OpenAPI spec version: 0.1.0
 */

export interface Metric {
  node_id: string;
  messages_in?: number;
  messages_out?: number;
  consumer_lag?: number;
  consumer_read_rate?: number;
  topic_size?: number;
  replicas?: number;
  replicas_available?: number;
  connector_tasks?: number;
}
