/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Streams Explorer
 * OpenAPI spec version: 0.1.0
 */
import type { NodeInfoListItemValue } from './nodeInfoListItemValue';
import type { NodeInfoType } from './nodeInfoType';

export interface NodeInfoListItem {
  name: string;
  value: NodeInfoListItemValue;
  type: NodeInfoType;
}
