/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Streams Explorer
 * OpenAPI spec version: 0.1.0
 */

/**
 * An enumeration.
 */
export type NodeTypesEnum = typeof NodeTypesEnum[keyof typeof NodeTypesEnum];

export const NodeTypesEnum = {
  "streaming-app": "streaming-app",
  connector: "connector",
  topic: "topic",
  "error-topic": "error-topic",
  "sink/source": "sink/source",
} as const;
