/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Streams Explorer
 * OpenAPI spec version: 0.1.0
 */

export interface Node {
  id: string;
  label: string;
  node_type: string;
  x?: number;
  y?: number;
}
