/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Streams Explorer
 * OpenAPI spec version: 0.1.0
 */
import type { NodeInfoListItem } from "./nodeInfoListItem";
import type { NodeTypesEnum } from "./nodeTypesEnum";

export interface NodeInformation {
  node_id: string;
  node_type: NodeTypesEnum;
  info: NodeInfoListItem[];
}
