/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Streams Explorer
 * OpenAPI spec version: 0.1.0
 */

/**
 * An enumeration.
 */
export type NodeInfoType = typeof NodeInfoType[keyof typeof NodeInfoType];

export const NodeInfoType = {
  json: "json",
  basic: "basic",
  link: "link",
} as const;
