/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Streams Explorer
 * OpenAPI spec version: 0.1.0
 */

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}
