{
 "title": "Consumer groups",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "consumergroups",
    "query": "kafka_consumergroup_group_sum_lag"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer groups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_consumergroup_group_sum_lag{group=~\".+\"})"
    },
    {}
   ]
  },
  {
   "title": "Active consumers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (client_id) (kafka_consumergroup_group_lag{client_id!=\"unknown\"}))"
    }
   ]
  },
  {
   "title": "Global lag",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_sum_lag{group=~\".+\"})"
    }
   ]
  },
  {
   "title": "Active consumer groups",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (group) (kafka_consumergroup_group_lag{group=~\".+\", client_id!=\"unknown\"} >= 0)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Rebalancing consumer groups",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum by(group) (label_replace(kafka_consumergroup_lag, \"group\", \"$1\", \"consumergroup\", \"(.*)\") >= 0) unless count by(group) (kafka_consumergroup_group_lag)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Inactive consumer groups",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum by (group) (kafka_consumergroup_group_lag{group=~\".+\",client_id=\"unknown\"} >= 0)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Read rate",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (group) (rate(kafka_consumergroup_group_offset{group=~\".+\"}[5m]) >= 0)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  { "title": "[[consumergroups]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "consumergroups" },
  {
   "title": "Active members",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (client_id) (kafka_consumergroup_group_lag{group=\"$consumergroups\", client_id!=\"unknown\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "$consumergroups topics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Lag" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_sum_lag{group=\"$consumergroups\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kafka_consumergroup_group_topic_sum_lag{group=\"$consumergroups\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$consumergroups topics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "rps", "label": "Read rate" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_group_offset{group=\"$consumergroups\"}[5m]) >= 0)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(topic) (rate(kafka_consumergroup_group_offset{group=\"$consumergroups\"}[5m]) >= 0)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$consumergroups topics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Offset" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_offset{group=\"$consumergroups\"} >= 0)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kafka_consumergroup_group_offset{group=\"$consumergroups\"} >= 0) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$consumergroups partitions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Lag" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{group=\"$consumergroups\"} >= 0) by (topic, partition)",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "$consumergroups members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Lag" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{group=\"$consumergroups\", client_id!=\"unknown\"} >= 0) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "$consumergroups members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "Number of partitions" }
   ],
   "targets": [
    {
     "expr": "count(kafka_consumergroup_group_lag{group=\"$consumergroups\", client_id!=\"unknown\"}) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}