{
 "title": "Topics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "topics",
    "query": "kafka_topic_partition_current_offset"
   }
  ]
 },
 "panels": [
  {
   "title": "Topics",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cp_kafka_controller_kafkacontroller_globaltopiccount)"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cp_kafka_controller_kafkacontroller_globalpartitioncount)"
    }
   ]
  },
  {
   "title": "Global",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_messagesinpersec) without (instance, statefulset_kubernetes_io_pod_name, kubernetes_pod_name, controller_revision_hash)",
     "legendFormat": "Messages in per sec"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesinpersec) without (instance, statefulset_kubernetes_io_pod_name, kubernetes_pod_name, controller_revision_hash)",
     "legendFormat": "Bytes in per sec"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesoutpersec) without (instance, statefulset_kubernetes_io_pod_name, kubernetes_pod_name, controller_revision_hash)",
     "legendFormat": "Bytes out per sec"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages out per second",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_consumergroup_group_offset[5m]) >= 0)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "[[topics]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "topics" },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_topic_partitions{topic=\"$topics\"})",
     "legendFormat": "Partitions"
    }
   ]
  },
  {
   "title": "$topics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"$topics\"}[5m]))",
     "legendFormat": "Messages in per sec"
    },
    {
     "expr": "sum(rate(kafka_consumergroup_group_offset{topic=\"$topics\"}[5m]))",
     "legendFormat": "Messages out per sec"
    }
   ]
  },
  {
   "title": "$topics consumer groups",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Lag" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_topic_sum_lag{topic=\"$topics\", group=~\".+\"}) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "$topics consumer groups",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Offset" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"$topics\"})",
     "legendFormat": "Latest"
    },
    {
     "expr": "sum(kafka_consumergroup_group_offset{topic=\"$topics\", group=~\".+\"} >= 0) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "$topics partitions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "Offset" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"$topics\"}) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  }
 ]
}