{{- if and .Values.rbac.create (not .Values.rbac.useExistingRole) .Values.rbac.clusterScope.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ include "streams-explorer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "streams-explorer.chart" . }}
  name: {{ template "streams-explorer.roleName" . }}
rules:
  - apiGroups: ["apps", "batch", "events"]
    resources: ["deployments", "cronjobs", "statefulsets", "events"]
    verbs: ["get", "list", "watch"]
{{- end -}}
