{{- if and .Values.rbac.create .Values.rbac.clusterScope.enabled -}}
{{- $root := . -}}
{{- range .Values.rbac.clusterScope.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "streams-explorer.name" $ }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
    helm.sh/chart: {{ include "streams-explorer.chart" $ }}
  name: {{ template "streams-explorer.fullname" $ }}
  namespace: {{ . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  {{- if (not $root.Values.rbac.useExistingRole) }}
  name: {{ template "streams-explorer.fullname" $ }}
  {{- else }}
  name: {{ $root.Values.rbac.useExistingRole }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    namespace: {{ $root.Release.Namespace }}
    {{- if (not $root.Values.rbac.useExisting) }}
    name: streams-explorer-sa
    {{- else }}
    name: {{ $root.Values.serviceAccount.useExisting }}
    {{- end }}
{{- end }}
{{- end }}