{{- if .Values.plugins }}
{{- $fullName := include "streams-explorer.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-plugins
  labels:
    app.kubernetes.io/name: {{ include "streams-explorer.name" . }}
    helm.sh/chart: {{ include "streams-explorer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.plugins }}
  {{ $key }}.py: |
{{ $value | indent 4 }}
  {{- end }}
{{ end }}