{{- if .Values.settings }}
{{- $fullName := include "streams-explorer.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-settings
  labels:
    app.kubernetes.io/name: {{ include "streams-explorer.name" . }}
    helm.sh/chart: {{ include "streams-explorer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  settings.yaml: |
    {{- tpl (toYaml .Values.settings) $ | nindent 4 }}
{{ end }}
