{{- $fullName := include "streams-explorer.fullname" . -}}
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2
{{- end }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.labels }}
  labels:
    app.kubernetes.io/name: {{ include "streams-explorer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "streams-explorer.chart" . }}
    {{- range $key, $value := .Values.deploymentLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "streams-explorer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "streams-explorer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "streams-explorer.chart" . }}
        {{- range $key, $value := .Values.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- if or .Values.awsRole  .Values.annotations }}
      annotations:
      {{- if .Values.awsRole }}
        iam.amazonaws.com/role: {{ .Values.awsRole }}
      {{- end }}
      {{- range $key, $value := .Values.annotations }}
        {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
      {{- if (not .Values.rbac.useExisting) }}
      serviceAccountName: streams-explorer-sa
      {{- else }}
      serviceAccountName: {{ .Values.serviceAccount.useExisting }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.serviceHttpPort}}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.health.livenessProbeInitialDelay }}
            periodSeconds: {{ .Values.health.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.health.livenessProbeTimeout }}
            failureThreshold: {{ .Values.health.livenessProbeFailureThreshold }}
            successThreshold: {{ .Values.health.livenessProbeSuccessThreshold }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: {{ .Values.health.readinessProbeInitialDelay }}
            periodSeconds: {{ .Values.health.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.health.readinessProbeTimeout }}
            failureThreshold: {{ .Values.health.readinessProbeFailureThreshold }}
            successThreshold: {{ .Values.health.readinessProbeSuccessThreshold }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
          {{- range $key, $value := .Values.secrets }}
            - name: "{{ $key }}"
              valueFrom:
                secretKeyRef:
                  name: {{ template "streams-explorer.fullname" $ }}
                  key: "{{ $key }}"
          {{- end }}
          {{- if .Values.rbac.clusterScope.enabled }}
            - name: "SE_K8S__deployment__namespaces"
              value: {{ .Values.rbac.clusterScope.namespaces | quote | replace " " ", " }}
          {{- end }}
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          volumeMounts:
          {{- if .Values.plugins }}
            - name: {{ $fullName }}-plugin-volume
              mountPath: /app/plugins
          {{ end }}
          {{- if .Values.icons }}
          {{- range $key, $value := .Values.icons }}
            - name: {{ $fullName }}-icons-volume
              mountPath: /app/static/{{ $key }}.svg
              subPath: {{ $key }}.svg
          {{ end }}
          {{ end }}
          {{- if .Values.volumeMounts }}{{ toYaml .Values.volumeMounts | trim | nindent 12 }}{{ end }}
      volumes:
      {{- if .Values.plugins }}
        - name: {{ $fullName }}-plugin-volume
          configMap:
            name: {{ $fullName }}-plugins
      {{ end }}
      {{- if .Values.icons }}
        - name: {{ $fullName }}-icons-volume
          configMap:
            name: {{ $fullName }}-icons
      {{ end }}
      {{- if .Values.volumes }}{{ toYaml .Values.volumes | trim | nindent 8 }}{{ end }}
