{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: {{ include "streams-explorer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "streams-explorer.chart" . }}
  name: {{ template "streams-explorer.fullname" . }}
rules:
  - apiGroups: ["apps", "batch"]
    resources: ["deployments", "cronjobs"]
    verbs: ["get", "list", "watch"]
{{- end -}}
