{{- if and .Values.rbac.create (not .Values.rbac.clusterScope.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "streams-explorer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "streams-explorer.chart" . }}
  name: {{ template "streams-explorer.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "streams-explorer.roleName" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ template "streams-explorer.serviceAccountName" . }}
{{- else if and .Values.rbac.create .Values.rbac.clusterScope.enabled -}}
{{- $root := . -}}
{{- range .Values.rbac.clusterScope.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "streams-explorer.name" $ }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
    helm.sh/chart: {{ include "streams-explorer.chart" $ }}
  name: {{ template "streams-explorer.fullname" $ }}- {{ $root.Release.Namespace }}
  namespace: {{ . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "streams-explorer.roleName" $ }}
subjects:
  - kind: ServiceAccount
    namespace: {{ $root.Release.Namespace }}
    name: {{ template "streams-explorer.serviceAccountName" $ }}
{{- end }}
{{- end }}
