{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "streams-explorer.fullname" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
