{{- if and .Values.rbac.create (not .Values.rbac.useExistingServiceAccount) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "streams-explorer.serviceAccountName" . }}
{{- end -}}
