{{- if and .Values.serviceAccount.create (not .Values.serviceAccount.useExisting) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if (not $root.Values.rbac.useExisting) }}
  name: streams-explorer-sa
  {{- else }}
  name: {{ $root.Values.serviceAccount.useExisting }}
  {{- end }}
{{- end -}}
