{{- if and .Values.serviceAccount.create (not .Values.serviceAccount.useExisting) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "streams-explorer.serviceAccountName" . }}
{{- end -}}
