{{- if and .Values.rbac.create (not .Values.rbac.useExistingServiceAccount) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "streams-explorer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "streams-explorer.chart" . }}
  name: {{ template "streams-explorer.serviceAccountName" . }}
{{- end -}}
