/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Streams Explorer
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetLinkingApiNodeLinkingNodeIdGetParams,
  GetNodeSchemaApiNodeNodeIdSchemaVersionGet200,
  GetPositionedGraphApiGraphGetParams,
  Graph,
  HTTPValidationError,
  Metric,
  NodeInformation,
  Pipelines
} from './model';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type updateApiUpdatePostResponse200 = {
  data: unknown
  status: 200
}

export type updateApiUpdatePostResponseSuccess = (updateApiUpdatePostResponse200) & {
  headers: Headers;
};
;

export type updateApiUpdatePostResponse = (updateApiUpdatePostResponseSuccess)

export const getUpdateApiUpdatePostUrl = () => {




  return `/api/update`
}

/**
 * @summary Update
 */
export const updateApiUpdatePost = async ( options?: RequestInit): Promise<updateApiUpdatePostResponse> => {

  const res = await fetch(getUpdateApiUpdatePostUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateApiUpdatePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateApiUpdatePostResponse
}




export const getUpdateApiUpdatePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateApiUpdatePost>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateApiUpdatePost>>, TError,void, TContext> => {

const mutationKey = ['updateApiUpdatePost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateApiUpdatePost>>, void> = () => {


          return  updateApiUpdatePost(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateApiUpdatePostMutationResult = NonNullable<Awaited<ReturnType<typeof updateApiUpdatePost>>>

    export type UpdateApiUpdatePostMutationError = unknown

    /**
 * @summary Update
 */
export const useUpdateApiUpdatePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateApiUpdatePost>>, TError,void, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateApiUpdatePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUpdateApiUpdatePostMutationOptions(options));
    }

export type getPositionedGraphApiGraphGetResponse200 = {
  data: Graph
  status: 200
}

export type getPositionedGraphApiGraphGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getPositionedGraphApiGraphGetResponseSuccess = (getPositionedGraphApiGraphGetResponse200) & {
  headers: Headers;
};
export type getPositionedGraphApiGraphGetResponseError = (getPositionedGraphApiGraphGetResponse422) & {
  headers: Headers;
};

export type getPositionedGraphApiGraphGetResponse = (getPositionedGraphApiGraphGetResponseSuccess | getPositionedGraphApiGraphGetResponseError)

export const getGetPositionedGraphApiGraphGetUrl = (params?: GetPositionedGraphApiGraphGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/graph?${stringifiedParams}` : `/api/graph`
}

/**
 * @summary Get Positioned Graph
 */
export const getPositionedGraphApiGraphGet = async (params?: GetPositionedGraphApiGraphGetParams, options?: RequestInit): Promise<getPositionedGraphApiGraphGetResponse> => {

  const res = await fetch(getGetPositionedGraphApiGraphGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPositionedGraphApiGraphGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPositionedGraphApiGraphGetResponse
}





export const getGetPositionedGraphApiGraphGetQueryKey = (params?: GetPositionedGraphApiGraphGetParams,) => {
    return [
    `/api/graph`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPositionedGraphApiGraphGetQueryOptions = <TData = Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>, TError = HTTPValidationError>(params?: GetPositionedGraphApiGraphGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPositionedGraphApiGraphGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>> = ({ signal }) => getPositionedGraphApiGraphGet(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPositionedGraphApiGraphGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>>
export type GetPositionedGraphApiGraphGetQueryError = HTTPValidationError


/**
 * @summary Get Positioned Graph
 */

export function useGetPositionedGraphApiGraphGet<TData = Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>, TError = HTTPValidationError>(
 params?: GetPositionedGraphApiGraphGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPositionedGraphApiGraphGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getPipelinesApiPipelinesGetResponse200 = {
  data: Pipelines
  status: 200
}

export type getPipelinesApiPipelinesGetResponseSuccess = (getPipelinesApiPipelinesGetResponse200) & {
  headers: Headers;
};
;

export type getPipelinesApiPipelinesGetResponse = (getPipelinesApiPipelinesGetResponseSuccess)

export const getGetPipelinesApiPipelinesGetUrl = () => {




  return `/api/pipelines`
}

/**
 * @summary Get Pipelines
 */
export const getPipelinesApiPipelinesGet = async ( options?: RequestInit): Promise<getPipelinesApiPipelinesGetResponse> => {

  const res = await fetch(getGetPipelinesApiPipelinesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPipelinesApiPipelinesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPipelinesApiPipelinesGetResponse
}





export const getGetPipelinesApiPipelinesGetQueryKey = () => {
    return [
    `/api/pipelines`
    ] as const;
    }


export const getGetPipelinesApiPipelinesGetQueryOptions = <TData = Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPipelinesApiPipelinesGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>> = ({ signal }) => getPipelinesApiPipelinesGet({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPipelinesApiPipelinesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>>
export type GetPipelinesApiPipelinesGetQueryError = unknown


/**
 * @summary Get Pipelines
 */

export function useGetPipelinesApiPipelinesGet<TData = Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPipelinesApiPipelinesGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getNodeInfoApiNodeNodeIdGetResponse200 = {
  data: NodeInformation
  status: 200
}

export type getNodeInfoApiNodeNodeIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getNodeInfoApiNodeNodeIdGetResponseSuccess = (getNodeInfoApiNodeNodeIdGetResponse200) & {
  headers: Headers;
};
export type getNodeInfoApiNodeNodeIdGetResponseError = (getNodeInfoApiNodeNodeIdGetResponse422) & {
  headers: Headers;
};

export type getNodeInfoApiNodeNodeIdGetResponse = (getNodeInfoApiNodeNodeIdGetResponseSuccess | getNodeInfoApiNodeNodeIdGetResponseError)

export const getGetNodeInfoApiNodeNodeIdGetUrl = (nodeId: string,) => {




  return `/api/node/${nodeId}`
}

/**
 * @summary Get Node Info
 */
export const getNodeInfoApiNodeNodeIdGet = async (nodeId: string, options?: RequestInit): Promise<getNodeInfoApiNodeNodeIdGetResponse> => {

  const res = await fetch(getGetNodeInfoApiNodeNodeIdGetUrl(nodeId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getNodeInfoApiNodeNodeIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getNodeInfoApiNodeNodeIdGetResponse
}





export const getGetNodeInfoApiNodeNodeIdGetQueryKey = (nodeId: string,) => {
    return [
    `/api/node/${nodeId}`
    ] as const;
    }


export const getGetNodeInfoApiNodeNodeIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>, TError = HTTPValidationError>(nodeId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeInfoApiNodeNodeIdGetQueryKey(nodeId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>> = ({ signal }) => getNodeInfoApiNodeNodeIdGet(nodeId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: nodeId !== null && nodeId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetNodeInfoApiNodeNodeIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>>
export type GetNodeInfoApiNodeNodeIdGetQueryError = HTTPValidationError


/**
 * @summary Get Node Info
 */

export function useGetNodeInfoApiNodeNodeIdGet<TData = Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>, TError = HTTPValidationError>(
 nodeId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetNodeInfoApiNodeNodeIdGetQueryOptions(nodeId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponse200 = {
  data: number[]
  status: 200
}

export type getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponseSuccess = (getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponse200) & {
  headers: Headers;
};
export type getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponseError = (getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponse422) & {
  headers: Headers;
};

export type getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponse = (getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponseSuccess | getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponseError)

export const getGetNodeSchemaVersionsApiNodeNodeIdSchemaGetUrl = (nodeId: string,) => {




  return `/api/node/${nodeId}/schema`
}

/**
 * @summary Get Node Schema Versions
 */
export const getNodeSchemaVersionsApiNodeNodeIdSchemaGet = async (nodeId: string, options?: RequestInit): Promise<getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponse> => {

  const res = await fetch(getGetNodeSchemaVersionsApiNodeNodeIdSchemaGetUrl(nodeId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getNodeSchemaVersionsApiNodeNodeIdSchemaGetResponse
}





export const getGetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryKey = (nodeId: string,) => {
    return [
    `/api/node/${nodeId}/schema`
    ] as const;
    }


export const getGetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryOptions = <TData = Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>, TError = HTTPValidationError>(nodeId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryKey(nodeId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>> = ({ signal }) => getNodeSchemaVersionsApiNodeNodeIdSchemaGet(nodeId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: nodeId !== null && nodeId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryResult = NonNullable<Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>>
export type GetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryError = HTTPValidationError


/**
 * @summary Get Node Schema Versions
 */

export function useGetNodeSchemaVersionsApiNodeNodeIdSchemaGet<TData = Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>, TError = HTTPValidationError>(
 nodeId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryOptions(nodeId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getNodeSchemaApiNodeNodeIdSchemaVersionGetResponse200 = {
  data: GetNodeSchemaApiNodeNodeIdSchemaVersionGet200
  status: 200
}

export type getNodeSchemaApiNodeNodeIdSchemaVersionGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getNodeSchemaApiNodeNodeIdSchemaVersionGetResponseSuccess = (getNodeSchemaApiNodeNodeIdSchemaVersionGetResponse200) & {
  headers: Headers;
};
export type getNodeSchemaApiNodeNodeIdSchemaVersionGetResponseError = (getNodeSchemaApiNodeNodeIdSchemaVersionGetResponse422) & {
  headers: Headers;
};

export type getNodeSchemaApiNodeNodeIdSchemaVersionGetResponse = (getNodeSchemaApiNodeNodeIdSchemaVersionGetResponseSuccess | getNodeSchemaApiNodeNodeIdSchemaVersionGetResponseError)

export const getGetNodeSchemaApiNodeNodeIdSchemaVersionGetUrl = (nodeId: string,
    version: number,) => {




  return `/api/node/${nodeId}/schema/${version}`
}

/**
 * @summary Get Node Schema
 */
export const getNodeSchemaApiNodeNodeIdSchemaVersionGet = async (nodeId: string,
    version: number, options?: RequestInit): Promise<getNodeSchemaApiNodeNodeIdSchemaVersionGetResponse> => {

  const res = await fetch(getGetNodeSchemaApiNodeNodeIdSchemaVersionGetUrl(nodeId,version),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getNodeSchemaApiNodeNodeIdSchemaVersionGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getNodeSchemaApiNodeNodeIdSchemaVersionGetResponse
}





export const getGetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryKey = (nodeId: string,
    version: number,) => {
    return [
    `/api/node/${nodeId}/schema/${version}`
    ] as const;
    }


export const getGetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryOptions = <TData = Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>, TError = HTTPValidationError>(nodeId: string,
    version: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryKey(nodeId,version);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>> = ({ signal }) => getNodeSchemaApiNodeNodeIdSchemaVersionGet(nodeId,version, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: nodeId !== null && nodeId !== undefined && version !== null && version !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryResult = NonNullable<Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>>
export type GetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryError = HTTPValidationError


/**
 * @summary Get Node Schema
 */

export function useGetNodeSchemaApiNodeNodeIdSchemaVersionGet<TData = Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>, TError = HTTPValidationError>(
 nodeId: string,
    version: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryOptions(nodeId,version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getLinkingApiNodeLinkingNodeIdGetResponse200 = {
  data: string
  status: 200
}

export type getLinkingApiNodeLinkingNodeIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getLinkingApiNodeLinkingNodeIdGetResponseSuccess = (getLinkingApiNodeLinkingNodeIdGetResponse200) & {
  headers: Headers;
};
export type getLinkingApiNodeLinkingNodeIdGetResponseError = (getLinkingApiNodeLinkingNodeIdGetResponse422) & {
  headers: Headers;
};

export type getLinkingApiNodeLinkingNodeIdGetResponse = (getLinkingApiNodeLinkingNodeIdGetResponseSuccess | getLinkingApiNodeLinkingNodeIdGetResponseError)

export const getGetLinkingApiNodeLinkingNodeIdGetUrl = (nodeId: string,
    params: GetLinkingApiNodeLinkingNodeIdGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/node/linking/${nodeId}?${stringifiedParams}` : `/api/node/linking/${nodeId}`
}

/**
 * @summary Get Linking
 */
export const getLinkingApiNodeLinkingNodeIdGet = async (nodeId: string,
    params: GetLinkingApiNodeLinkingNodeIdGetParams, options?: RequestInit): Promise<getLinkingApiNodeLinkingNodeIdGetResponse> => {

  const res = await fetch(getGetLinkingApiNodeLinkingNodeIdGetUrl(nodeId,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getLinkingApiNodeLinkingNodeIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getLinkingApiNodeLinkingNodeIdGetResponse
}





export const getGetLinkingApiNodeLinkingNodeIdGetQueryKey = (nodeId: string,
    params?: GetLinkingApiNodeLinkingNodeIdGetParams,) => {
    return [
    `/api/node/linking/${nodeId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLinkingApiNodeLinkingNodeIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>, TError = HTTPValidationError>(nodeId: string,
    params: GetLinkingApiNodeLinkingNodeIdGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLinkingApiNodeLinkingNodeIdGetQueryKey(nodeId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>> = ({ signal }) => getLinkingApiNodeLinkingNodeIdGet(nodeId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: nodeId !== null && nodeId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLinkingApiNodeLinkingNodeIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>>
export type GetLinkingApiNodeLinkingNodeIdGetQueryError = HTTPValidationError


/**
 * @summary Get Linking
 */

export function useGetLinkingApiNodeLinkingNodeIdGet<TData = Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetLinkingApiNodeLinkingNodeIdGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetLinkingApiNodeLinkingNodeIdGetQueryOptions(nodeId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getMetricsApiMetricsGetResponse200 = {
  data: Metric[]
  status: 200
}

export type getMetricsApiMetricsGetResponseSuccess = (getMetricsApiMetricsGetResponse200) & {
  headers: Headers;
};
;

export type getMetricsApiMetricsGetResponse = (getMetricsApiMetricsGetResponseSuccess)

export const getGetMetricsApiMetricsGetUrl = () => {




  return `/api/metrics`
}

/**
 * @summary Get Metrics
 */
export const getMetricsApiMetricsGet = async ( options?: RequestInit): Promise<getMetricsApiMetricsGetResponse> => {

  const res = await fetch(getGetMetricsApiMetricsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMetricsApiMetricsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMetricsApiMetricsGetResponse
}





export const getGetMetricsApiMetricsGetQueryKey = () => {
    return [
    `/api/metrics`
    ] as const;
    }


export const getGetMetricsApiMetricsGetQueryOptions = <TData = Awaited<ReturnType<typeof getMetricsApiMetricsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMetricsApiMetricsGet>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMetricsApiMetricsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetricsApiMetricsGet>>> = ({ signal }) => getMetricsApiMetricsGet({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMetricsApiMetricsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMetricsApiMetricsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMetricsApiMetricsGet>>>
export type GetMetricsApiMetricsGetQueryError = unknown


/**
 * @summary Get Metrics
 */

export function useGetMetricsApiMetricsGet<TData = Awaited<ReturnType<typeof getMetricsApiMetricsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMetricsApiMetricsGet>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMetricsApiMetricsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}
