/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Streams Explorer
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetLinkingApiNodeLinkingNodeIdGetParams,
  GetNodeSchemaApiNodeNodeIdSchemaVersionGet200,
  GetPositionedGraphApiGraphGetParams,
  Graph,
  HTTPValidationError,
  Metric,
  NodeInformation,
  Pipelines
} from './model';

import { customInstance } from './mutator';
import type { ErrorType } from './mutator';
type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Update
 */
export const updateApiUpdatePost = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/update`, method: 'POST', signal
    },
      options);
    }



export const getUpdateApiUpdatePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateApiUpdatePost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateApiUpdatePost>>, TError,void, TContext> => {

const mutationKey = ['updateApiUpdatePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateApiUpdatePost>>, void> = () => {


          return  updateApiUpdatePost(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateApiUpdatePostMutationResult = NonNullable<Awaited<ReturnType<typeof updateApiUpdatePost>>>

    export type UpdateApiUpdatePostMutationError = ErrorType<unknown>

    /**
 * @summary Update
 */
export const useUpdateApiUpdatePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateApiUpdatePost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateApiUpdatePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUpdateApiUpdatePostMutationOptions(options));
    }

/**
 * @summary Get Positioned Graph
 */
export const getPositionedGraphApiGraphGet = (
    params?: GetPositionedGraphApiGraphGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Graph>(
      {url: `/api/graph`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetPositionedGraphApiGraphGetQueryKey = (params?: GetPositionedGraphApiGraphGetParams,) => {
    return [
    `/api/graph`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPositionedGraphApiGraphGetQueryOptions = <TData = Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>, TError = ErrorType<HTTPValidationError>>(params?: GetPositionedGraphApiGraphGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPositionedGraphApiGraphGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>> = ({ signal }) => getPositionedGraphApiGraphGet(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPositionedGraphApiGraphGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>>
export type GetPositionedGraphApiGraphGetQueryError = ErrorType<HTTPValidationError>


/**
 * @summary Get Positioned Graph
 */

export function useGetPositionedGraphApiGraphGet<TData = Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetPositionedGraphApiGraphGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPositionedGraphApiGraphGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPositionedGraphApiGraphGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Get Pipelines
 */
export const getPipelinesApiPipelinesGet = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Pipelines>(
      {url: `/api/pipelines`, method: 'GET', signal
    },
      options);
    }




export const getGetPipelinesApiPipelinesGetQueryKey = () => {
    return [
    `/api/pipelines`
    ] as const;
    }


export const getGetPipelinesApiPipelinesGetQueryOptions = <TData = Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPipelinesApiPipelinesGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>> = ({ signal }) => getPipelinesApiPipelinesGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPipelinesApiPipelinesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>>
export type GetPipelinesApiPipelinesGetQueryError = ErrorType<unknown>


/**
 * @summary Get Pipelines
 */

export function useGetPipelinesApiPipelinesGet<TData = Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPipelinesApiPipelinesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPipelinesApiPipelinesGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Get Node Info
 */
export const getNodeInfoApiNodeNodeIdGet = (
    nodeId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<NodeInformation>(
      {url: `/api/node/${nodeId}`, method: 'GET', signal
    },
      options);
    }




export const getGetNodeInfoApiNodeNodeIdGetQueryKey = (nodeId: string,) => {
    return [
    `/api/node/${nodeId}`
    ] as const;
    }


export const getGetNodeInfoApiNodeNodeIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>, TError = ErrorType<HTTPValidationError>>(nodeId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeInfoApiNodeNodeIdGetQueryKey(nodeId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>> = ({ signal }) => getNodeInfoApiNodeNodeIdGet(nodeId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: nodeId !== null && nodeId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetNodeInfoApiNodeNodeIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>>
export type GetNodeInfoApiNodeNodeIdGetQueryError = ErrorType<HTTPValidationError>


/**
 * @summary Get Node Info
 */

export function useGetNodeInfoApiNodeNodeIdGet<TData = Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>, TError = ErrorType<HTTPValidationError>>(
 nodeId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeInfoApiNodeNodeIdGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetNodeInfoApiNodeNodeIdGetQueryOptions(nodeId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Get Node Schema Versions
 */
export const getNodeSchemaVersionsApiNodeNodeIdSchemaGet = (
    nodeId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<number[]>(
      {url: `/api/node/${nodeId}/schema`, method: 'GET', signal
    },
      options);
    }




export const getGetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryKey = (nodeId: string,) => {
    return [
    `/api/node/${nodeId}/schema`
    ] as const;
    }


export const getGetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryOptions = <TData = Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>, TError = ErrorType<HTTPValidationError>>(nodeId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryKey(nodeId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>> = ({ signal }) => getNodeSchemaVersionsApiNodeNodeIdSchemaGet(nodeId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: nodeId !== null && nodeId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryResult = NonNullable<Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>>
export type GetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryError = ErrorType<HTTPValidationError>


/**
 * @summary Get Node Schema Versions
 */

export function useGetNodeSchemaVersionsApiNodeNodeIdSchemaGet<TData = Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>, TError = ErrorType<HTTPValidationError>>(
 nodeId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaVersionsApiNodeNodeIdSchemaGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetNodeSchemaVersionsApiNodeNodeIdSchemaGetQueryOptions(nodeId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Get Node Schema
 */
export const getNodeSchemaApiNodeNodeIdSchemaVersionGet = (
    nodeId: string,
    version: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetNodeSchemaApiNodeNodeIdSchemaVersionGet200>(
      {url: `/api/node/${nodeId}/schema/${version}`, method: 'GET', signal
    },
      options);
    }




export const getGetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryKey = (nodeId: string,
    version: number,) => {
    return [
    `/api/node/${nodeId}/schema/${version}`
    ] as const;
    }


export const getGetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryOptions = <TData = Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>, TError = ErrorType<HTTPValidationError>>(nodeId: string,
    version: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryKey(nodeId,version);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>> = ({ signal }) => getNodeSchemaApiNodeNodeIdSchemaVersionGet(nodeId,version, requestOptions, signal);





   return  { queryKey, queryFn, enabled: nodeId !== null && nodeId !== undefined && version !== null && version !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryResult = NonNullable<Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>>
export type GetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryError = ErrorType<HTTPValidationError>


/**
 * @summary Get Node Schema
 */

export function useGetNodeSchemaApiNodeNodeIdSchemaVersionGet<TData = Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>, TError = ErrorType<HTTPValidationError>>(
 nodeId: string,
    version: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNodeSchemaApiNodeNodeIdSchemaVersionGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetNodeSchemaApiNodeNodeIdSchemaVersionGetQueryOptions(nodeId,version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Get Linking
 */
export const getLinkingApiNodeLinkingNodeIdGet = (
    nodeId: string,
    params: GetLinkingApiNodeLinkingNodeIdGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<string>(
      {url: `/api/node/linking/${nodeId}`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetLinkingApiNodeLinkingNodeIdGetQueryKey = (nodeId: string,
    params?: GetLinkingApiNodeLinkingNodeIdGetParams,) => {
    return [
    `/api/node/linking/${nodeId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLinkingApiNodeLinkingNodeIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>, TError = ErrorType<HTTPValidationError>>(nodeId: string,
    params: GetLinkingApiNodeLinkingNodeIdGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLinkingApiNodeLinkingNodeIdGetQueryKey(nodeId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>> = ({ signal }) => getLinkingApiNodeLinkingNodeIdGet(nodeId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: nodeId !== null && nodeId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLinkingApiNodeLinkingNodeIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>>
export type GetLinkingApiNodeLinkingNodeIdGetQueryError = ErrorType<HTTPValidationError>


/**
 * @summary Get Linking
 */

export function useGetLinkingApiNodeLinkingNodeIdGet<TData = Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>, TError = ErrorType<HTTPValidationError>>(
 nodeId: string,
    params: GetLinkingApiNodeLinkingNodeIdGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLinkingApiNodeLinkingNodeIdGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetLinkingApiNodeLinkingNodeIdGetQueryOptions(nodeId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Get Metrics
 */
export const getMetricsApiMetricsGet = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Metric[]>(
      {url: `/api/metrics`, method: 'GET', signal
    },
      options);
    }




export const getGetMetricsApiMetricsGetQueryKey = () => {
    return [
    `/api/metrics`
    ] as const;
    }


export const getGetMetricsApiMetricsGetQueryOptions = <TData = Awaited<ReturnType<typeof getMetricsApiMetricsGet>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMetricsApiMetricsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMetricsApiMetricsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetricsApiMetricsGet>>> = ({ signal }) => getMetricsApiMetricsGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMetricsApiMetricsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMetricsApiMetricsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMetricsApiMetricsGet>>>
export type GetMetricsApiMetricsGetQueryError = ErrorType<unknown>


/**
 * @summary Get Metrics
 */

export function useGetMetricsApiMetricsGet<TData = Awaited<ReturnType<typeof getMetricsApiMetricsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMetricsApiMetricsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMetricsApiMetricsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}
