nameOverride: atm-fraud-frauddetector

replicaCount: 1

image: url-to-container-registry.com/streams-explorer-demo-frauddetector
imageTag: latest

streams:
  brokers: "kafka://my-confluent-cp-kafka-headless:9092"
  schemaRegistryUrl: "http://my-confluent-cp-schema-registry:8081"
  inputTopics:
    - atm-fraud-joinedtransactions-topic
  outputTopic: atm-fraud-possiblefraudtransactions-topic
  errorTopic: atm-fraud-frauddetector-error-topic

annotations:
  consumerGroup: "streams-explorer-frauddetector-atm-fraud-possiblefraudtransactions-topic"

prometheus:
  jmx:
    enabled: false

debug: true
