nameOverride: atm-fraud-accountlinker

replicaCount: 1

image: url-to-container-registry.com/streams-explorer-demo-accountlinker
imageTag: latest

streams:
  brokers: "kafka://my-confluent-cp-kafka-headless:9092"
  schemaRegistryUrl: "http://my-confluent-cp-schema-registry:8081"
  inputTopics: atm-fraud-possiblefraudtransactions-topic
  extraInputTopics:
    accounts: atm-fraud-accounts-topic
  outputTopic: atm-fraud-output-topic
  errorTopic: atm-fraud-accountlinker-error-topic

annotations:
  consumerGroup: "streams-explorer-accountlinker-atm-fraud-output-topic"

prometheus:
  jmx:
    enabled: false

debug: true
