nameOverride: atm-fraud-transactionjoiner

replicaCount: 1

image: url-to-container-registry.com/streams-explorer-demo-transactionjoiner
imageTag: latest

streams:
  brokers: "kafka://my-confluent-cp-kafka-headless:9092"
  schemaRegistryUrl: "http://my-confluent-cp-schema-registry:8081"
  inputTopics:
    - atm-fraud-incoming-transactions-topic
  outputTopic: atm-fraud-joinedtransactions-topic
  errorTopic: atm-fraud-transactionjoiner-error-topic

annotations:
  consumerGroup: "streams-explorer-transactionjoiner-atm-fraud-joinedtransactions-topic"

prometheus:
  jmx:
    enabled: false

debug: true
