name: Update Docker base image

on:
  workflow_dispatch:
  push:

jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      image: bakdata/streams-explorer-base
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:backend"
          push: false # TODO: enable
          tags: ${{ env.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
