name: Docker base image

on:
  workflow_dispatch:

jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      image: bakdata/streams-explorer-base
      working-directory: ./backend
    steps:
      - uses: actions/checkout@v3

      - run: cd ${{ env.working_directory }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.image }}
          tags: |
            event=pr,type=sha
            event=tag,type=semver,pattern=v{{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          # context: "{{defaultContext}}:backend"
          push: false # TODO: enable
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
