name: Publish

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  pypi:
    name: PyPI
    needs: [backend, frontend, docker]
    runs-on: ubuntu-latest
    env:
      BACKEND_DIR: ./backend
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/checkout@v3
        with:
          repository: bakdata/ci-templates
          path: ci-templates

      - name: Copy Readme
        run: |
          cp README.md $BACKEND_DIR/
          git add $BACKEND_DIR/README.md
          sed -E -i.bak 's/\.\.\/README/README/' $BACKEND_DIR/pyproject.toml

      - name: Install packages
        run: sudo apt-get -y install python3-dev graphviz libgraphviz-dev pkg-config python3-wheel

      - name: Release to TestPyPI
        uses: ./ci-templates/actions/python-poetry-release
        with:
          working-directory: ${{ env.BACKEND_DIR }}
          pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}
          publish-to-test: "true"

      - name: Release to PyPI
        uses: ./ci-templates/actions/python-poetry-release
        with:
          working-directory: ${{ env.BACKEND_DIR }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          publish-to-test: "false"
