name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Scope of the release; See: https://python-poetry.org/docs/cli/#version"
        default: "patch"
        required: false

jobs:
  bump-version:
    name: Bump version
    needs: [backend, frontend, docker]
    runs-on: ubuntu-latest
    env:
      BACKEND_DIR: ./backend
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Bump version
        id: bump-version
        uses: bakdata/ci-templates/actions/python-poetry-bump-version@v1.0.0
        with:
          release-type: "${{ github.event.inputs.release-type }}"
          working-directory: ${{ env.BACKEND_DIR }}

      - name: Commit and push pyproject.toml file
        uses: bakdata/ci-templates/actions/commit-and-push@v1.0.0
        with:
          ref: ${{ inputs.ref }}
          commit-message: "Bump version ${{ steps.bump-version.outputs.old-tag }} → ${{ steps.bump-version.outputs.release-tag }}"
          github-username: ${{ secrets.github-username }}
          github-email: ${{ secrets.github-email }}
          github-token: ${{ secrets.github-token }}

      - name: Create and push tag
        run: |
          git tag v${{ steps.bump-version.outputs.release-tag }}
          git push origin v${{ steps.bump-version.outputs.release-tag }}
